services:
  inspircd:
    image: "inspircd/inspircd-docker"
    restart: always
    networks:
      - backend
  tor:
    build: "./tor"
    networks:
      - backend
    volumes:
      - "./tor/torrc:/etc/tor/torrc"
      - "./tor/hidden_service:/var/lib/tor/hidden_service"
    restart: always
  filegator:
    container_name: filegator
    image: filegator/filegator
    restart: always
    networks:
      - backend
    volumes:
      - ./filegator/files:/var/www/filegator/repository
      - ./filegator/users.json:/var/www/filegator/private/users.json

networks:
  backend:
    driver: bridge
