services:
  inspircd:
    image: "inspircd/inspircd-docker"
    restart: always
    networks:
      - backend
    # volumes:
      # - "./inspircd/conf:/inspircd/conf" # uncomment after first run
    environment:
      - INSP_NET_SUFFIX=.onion
      - INSP_NET_NAME=TorIrc
      - INSP_SERVER_NAME=torirc
      - INSP_CONNECT_PASSWORD=password
  tor:
    build: "./tor"
    networks:
      - backend
      - internet
    #volumes:
      #- "./tor/torrc:/etc/tor/torrc"
      #- "./tor/hidden_service:/var/lib/tor/hidden_service" # uncomment after first run
    restart: always
  filegator:
    container_name: filegator
    image: filegator/filegator
    restart: always
    networks:
      - backend
    volumes:
      - ./filegator/files:/var/www/filegator/repository
      - ./filegator/users.json:/var/www/filegator/private/users.json

networks:
  backend:
    driver: bridge
    internal: true
  internet:
    driver: bridge
