services:
  inspircd:
    image: "inspircd/inspircd-docker"
    restart: always
    networks:
      - backend
  tor:
    build: "./tor"
    networks:
      - backend
    volumes:
      - "./tor/torrc:/etc/tor/torrc"
      - "./tor/hidden_service:/var/lib/tor/hidden_service"
    restart: always
  vsftpd:
    image: "fauria/vsftpd"
    volumes:
      - "./vsftpd:/home/vsftpd"
    networks:
      - backend
    environment:
      - FTP_USER=ftp
      - FTP_PASS=ftp
    restart: always

networks:
  backend:
    driver: bridge
